<?php
/*
Plugin Name: Bangladesh Map
Plugin URI: http://www.jamunait.com/
Description: Bangladesh Map
Author: Emran Hossen
Version: 2.0
Author URI: http://ceo.jamunait.com/
*/


// Block direct requests
if ( !defined('ABSPATH') )
die('-1');
add_action( 'widgets_init', function(){
register_widget( 'Bangladesh_Map' );
});
/**
* Adds Bangladesh_Map widget.
*/
class Bangladesh_Map extends WP_Widget {
/**
* Register widget with WordPress.
*/
function __construct() {
parent::__construct(
'Bangladesh_Map', // Base ID
__('Bangladesh Map', 'text_domain'), // Name
array( 'description' => __( 'Bangladesh Map', 'text_domain' ), ) // Args
);
}

/**
* Front-end display of widget.
*
* @see WP_Widget::widget()
*
* @param array $args Widget arguments.
* @param array $instance Saved values from database.
*/
public function widget( $args, $instance ) {
echo $args['before_widget'];
if ( ! empty( $instance['title'] ) ) {
echo $args['before_title'] . apply_filters( 'widget_title', $instance['title'] ). $args['after_title'];
}
echo __( '<iframe id="player" width="330" height="500" frameborder="0" scrolling="no"
src="/wp-content/plugins/bangladesh-map/map/index.html' . $key . '" ></iframe>' );
echo $args['after_widget'];
}
/**
* Back-end widget form.
*
* @see WP_Widget::form()
*
* @param array $instance Previously saved values from database.
*/
public function form( $instance ) {
if ( isset( $instance[ 'title' ] ) ) {
$title = $instance[ 'title' ];
}
else {
$title = __( '', 'text_domain' );
}
?>
	<p>
<label for="<?php echo $this->get_field_id( 'title' ); ?>"><?php _e( 'Title:' ); ?></label>
<input class="widefat" id="<?php echo $this->get_field_id( 'title' ); ?>" name="<?php echo $this->get_field_name( 'title' ); ?>" type="text" value="<?php echo esc_attr( $title ); ?>">
</p> 
<?php
}

/**
* Sanitize widget form values as they are saved.
*
* @see WP_Widget::update()
*
* @param array $new_instance Values just sent to be saved.
* @param array $old_instance Previously saved values from database.
*
* @return array Updated safe values to be saved.
*/

public function update( $new_instance, $old_instance ) {
$instance = array();
$instance['title'] = ( ! empty( $new_instance['title'] ) ) ? strip_tags( $new_instance['title'] ) : '';
return $instance;
}
}

//tell wordpress to register the demolistposts shortcode
add_shortcode("bangladesh_map", "bangladeshmap_handler");

function bangladeshmap_handler() {
  //run function that actually does the work of the plugin
  $bdmap_output = bangladeshmap_function();
  //send back text to replace shortcode in post
  return $bdmap_output;
}

function bangladeshmap_function() {
  //process plugin
  $bdmap_output = '<iframe id="player" width="330" height="500" frameborder="0" scrolling="no"
src="/wp-content/plugins/bangladesh-map/map/index.html' . $key . '" ></iframe>';
  //send back text to calling function
  return $bdmap_output;
}

//marketing materials for buyers wordpress menu
add_action( 'admin_menu', 'register_bangladesh_map_menu_page' );

function register_bangladesh_map_menu_page(){
     add_menu_page( "Bangladesh Map", "Bangladesh Map", "manage_options", "bangladesh-map", "bangladesh_map_function", plugins_url( 'bangladesh-map/map/file/icon.png' ) );
 add_submenu_page( "bangladesh-map", "Installation", "Installation", "manage_options", "bangladesh-map-installation","add_installation_function");
 add_submenu_page( "bangladesh-map", "Districts Code", "Districts Code", "manage_options", "bangladesh-map-districts-code","add_districts_function");
 

} 
function bangladesh_map_function(){
  { print "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n";
print "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n";
print "<head>\n";
print "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n";
print "<title>Bangladesh Map</title>\n";
print "</head>\n";
print "\n";
print "<body>\n";
print "<center><h2>Welcome to Bangladesh Map </h2>\n";
print "Thank you for using this plugin. You can call me for any problems or help.\n";
print "<p>Shortcode : [bangladesh_map] </p>\n";
print "<p>Phpcode : &lt;?php echo do_shortcode('[bangladesh_map]');?&gt;  </p>\n";
print "<p>Phone : 01779-520000 </p>\n";
print "<p>Email : info@jamunait.com  </p>\n";
print "<p><a href=\"http://www.jamunait.com/bangladesh_map.php\" target=\"_blank\" style=\"text-decoration: none\" >Click here for demo</a>  </p>\n";
print "<p>  </p><p>  </p><p>    </p><p>    </p>\n";
print "Powered by <a href=\"http://www.jamunait.com/\" target=\"_blank\">\n";
print "<img src=\"http://www.jamunait.com/images/slogo.png\" alt=\"\" title=\"\" border=\"0\" width=\"132\" height=\"32\" /></a>\n";
print "</center>\n";
print "</body>\n";
print "</html>";

}

}





//lead generation wordpress sub menu

function add_installation_function(){

     {
 print "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n";
print "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n";
print "<head>\n";
print "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n";
print "<title>Installation</title>\n";
print "</head>\n";
print "\n";
print "<body>\n";
print "<center>\n";
print "<h2>Installation</h2></center>\n";
print "1. Settings → Permalinks → Post name → /%category%/%postname%/ → Category base → . (Dot) → Save Changes.\n";
print "<P>\n";
print "<img src=\"/wp-content/plugins/bangladesh-map/map/file/Installation1.png\" width=\"100%\" height=\"500\" /></P>\n";
print "<p>  </p><p>  </p>\n";
print "<P>2.  Bangladesh Map → Districts code → Use Category name and Slug properly.\n";
print "</P><img src=\"/wp-content/plugins/bangladesh-map/map/file/Installation2.png\" width=\"100%\" height=\"628\" />\n";
print "</P>\n";
print "<p>  </p><p>  </p>\n";
print "<P>3. Posts → Categories → Add New Category using Districts code.\n";
print "</P><img src=\"/wp-content/plugins/bangladesh-map/map/file/Installation3.png\" width=\"100%\" height=\"628\" /></P>\n";
print "<p>  </p><p>  </p>\n";
print "<P>4. Appearance → Widgets → Add Bangladesh Map where you want → Save Changes.\n";
print "</P><img src=\"/wp-content/plugins/bangladesh-map/map/file/Installation4.png\" width=\"100%\" height=\"628\" />\n";
print "<p>  </p><p>  </p>\n";
print "\n";
print "<center>Powered by <a href=\"http://www.jamunait.com/\" target=\"_blank\">\n";
print "<img src=\"http://www.jamunait.com/images/slogo.png\" alt=\"\" title=\"\" border=\"0\" width=\"132\" height=\"32\" hspace=\"10\"/></a></center>\n";
print "<p>  </p><p>  </p>\n";
print "</body>\n";
print "</html>\n";
;
}

}

//ad campaign wordpress sub menu

function add_districts_function(){

   { print "<html xmlns:o=\"urn:schemas-microsoft-com:office:office\"\n";
print "xmlns:w=\"urn:schemas-microsoft-com:office:word\"\n";
print "xmlns=\"http://www.w3.org/TR/REC-html40\">\n";
print "\n";
print "<head>\n";
print "<meta http-equiv=Content-Type content=\"text/html; charset=windows-1252\">\n";
print "<meta name=ProgId content=Word.Document>\n";
print "<meta name=Generator content=\"Microsoft Word 11\">\n";
print "<meta name=Originator content=\"Microsoft Word 11\">\n";
print "<link rel=File-List href=\"Districts%20code_files/filelist.xml\">\n";
print "<title>Districts code</title>\n";
print "<!--[if gte mso 9]><xml>\n";
print " <o:DocumentProperties>\n";
print "  <o:Author>Esoft</o:Author>\n";
print "  <o:Template>Normal</o:Template>\n";
print "  <o:LastAuthor>Esoft</o:LastAuthor>\n";
print "  <o:Revision>3</o:Revision>\n";
print "  <o:TotalTime>5</o:TotalTime>\n";
print "  <o:Created>2015-04-26T17:09:00Z</o:Created>\n";
print "  <o:LastSaved>2015-04-26T17:14:00Z</o:LastSaved>\n";
print "  <o:Pages>1</o:Pages>\n";
print "  <o:Words>255</o:Words>\n";
print "  <o:Characters>1456</o:Characters>\n";
print "  <o:Company><arabianhorse></o:Company>\n";
print "  <o:Lines>12</o:Lines>\n";
print "  <o:Paragraphs>3</o:Paragraphs>\n";
print "  <o:CharactersWithSpaces>1708</o:CharactersWithSpaces>\n";
print "  <o:Version>11.6568</o:Version>\n";
print " </o:DocumentProperties>\n";
print "</xml><![endif]--><!--[if gte mso 9]><xml>\n";
print " <w:WordDocument>\n";
print "  <w:SpellingState>Clean</w:SpellingState>\n";
print "  <w:GrammarState>Clean</w:GrammarState>\n";
print "  <w:PunctuationKerning/>\n";
print "  <w:ValidateAgainstSchemas/>\n";
print "  <w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>\n";
print "  <w:IgnoreMixedContent>false</w:IgnoreMixedContent>\n";
print "  <w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>\n";
print "  <w:Compatibility>\n";
print "   <w:BreakWrappedTables/>\n";
print "   <w:SnapToGridInCell/>\n";
print "   <w:WrapTextWithPunct/>\n";
print "   <w:UseAsianBreakRules/>\n";
print "   <w:DontGrowAutofit/>\n";
print "  </w:Compatibility>\n";
print "  <w:BrowserLevel>MicrosoftInternetExplorer4</w:BrowserLevel>\n";
print " </w:WordDocument>\n";
print "</xml><![endif]--><!--[if gte mso 9]><xml>\n";
print " <w:LatentStyles DefLockedState=\"false\" LatentStyleCount=\"156\">\n";
print " </w:LatentStyles>\n";
print "</xml><![endif]-->\n";
print "<style>\n";
print "<!--\n";
print " /* Font Definitions */\n";
print " @font-face\n";
print "	{font-family:Vrinda;\n";
print "	panose-1:2 11 5 2 4 2 4 2 2 3;\n";
print "	mso-font-charset:0;\n";
print "	mso-generic-font-family:swiss;\n";
print "	mso-font-pitch:variable;\n";
print "	mso-font-signature:65539 0 0 0 1 0;}\n";
print " /* Style Definitions */\n";
print " p.MsoNormal, li.MsoNormal, div.MsoNormal\n";
print "	{mso-style-parent:\"\";\n";
print "	margin:0in;\n";
print "	margin-bottom:.0001pt;\n";
print "	mso-pagination:widow-orphan;\n";
print "	font-size:12.0pt;\n";
print "	font-family:\"Times New Roman\";\n";
print "	mso-fareast-font-family:\"Times New Roman\";}\n";
print "h1\n";
print "	{mso-margin-top-alt:auto;\n";
print "	margin-right:0in;\n";
print "	mso-margin-bottom-alt:auto;\n";
print "	margin-left:0in;\n";
print "	mso-pagination:widow-orphan;\n";
print "	mso-outline-level:1;\n";
print "	font-size:24.0pt;\n";
print "	font-family:\"Times New Roman\";}\n";
print "span.SpellE\n";
print "	{mso-style-name:\"\";\n";
print "	mso-spl-e:yes;}\n";
print "@page Section1\n";
print "	{size:8.5in 11.0in;\n";
print "	margin:1.0in .6in 1.0in .6in;\n";
print "	mso-header-margin:.5in;\n";
print "	mso-footer-margin:.5in;\n";
print "	mso-paper-source:0;}\n";
print "div.Section1\n";
print "	{page:Section1;}\n";
print "-->\n";
print "</style>\n";
print "<!--[if gte mso 10]>\n";
print "<style>\n";
print " /* Style Definitions */\n";
print " table.MsoNormalTable\n";
print "	{mso-style-name:\"Table Normal\";\n";
print "	mso-tstyle-rowband-size:0;\n";
print "	mso-tstyle-colband-size:0;\n";
print "	mso-style-noshow:yes;\n";
print "	mso-style-parent:\"\";\n";
print "	mso-padding-alt:0in 5.4pt 0in 5.4pt;\n";
print "	mso-para-margin:0in;\n";
print "	mso-para-margin-bottom:.0001pt;\n";
print "	mso-pagination:widow-orphan;\n";
print "	font-size:10.0pt;\n";
print "	font-family:\"Times New Roman\";\n";
print "	mso-ansi-language:#0400;\n";
print "	mso-fareast-language:#0400;\n";
print "	mso-bidi-language:#0400;}\n";
print "</style>\n";
print "<![endif]-->\n";
print "</head>\n";
print "\n";
print "<body lang=EN-US style='tab-interval:.5in'>\n";
print "\n";
print "<div class=Section1>\n";
print "\n";
print "<h1 align=center style='text-align:center'><span style='font-size:14.0pt;\n";
print "font-family:Arial;color:black'>Districts code<o:p></o:p></span></h1>\n";
print "\n";
print "<div align=center>\n";
print "\n";
print "<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=640\n";
print " style='width:479.75pt;margin-left:-42.3pt;border-collapse:collapse;mso-padding-alt:\n";
print " 0in 0in 0in 0in' u1:str>\n";
print " <colgroup><col style=\"mso-width-source:userset;mso-width-alt:3328;width:68pt\" width=\"91\"><col style=\"mso-width-source:userset;mso-width-alt:3547;width:73pt\" width=\"97\"><col style=\"mso-width-source:userset;mso-width-alt:3108;width:64pt\" width=\"85\"><col style=\"mso-width-source:userset;mso-width-alt:2816;width:58pt\" width=\"77\"><col style=\"mso-width-source:userset;mso-width-alt:3657;width:75pt\" width=\"100\"><col style=\"mso-width-source:userset;mso-width-alt:3364;width:69pt\" width=\"92\"></colgroup>\n";
print " <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;height:12.75pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:12.75pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:12.75pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=74 style='width:55.8pt;padding:0in 0in 0in 0in;height:12.75pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:12.75pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:12.75pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:12.75pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:1;height:.25in'>\n";
print "  <td width=243 colspan=2 style='width:182.5pt;padding:0in 0in 0in 0in;\n";
print "  height:.25in'>\n";
print "  <p class=MsoNormal align=center style='text-align:center'><span class=SpellE><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>ঢাক</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>া</span><span\n";
print "  style='font-size:14.0pt'> </span><span class=SpellE><span style='font-size:\n";
print "  14.0pt;font-family:Vrinda'>বিভাগ</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=274 colspan=2 style='width:205.75pt;padding:0in 0in 0in 0in;\n";
print "  height:.25in'>\n";
print "  <p class=MsoNormal align=center style='text-align:center'><span class=SpellE><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>খুলন</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>া</span><span\n";
print "  style='font-size:14.0pt'> </span><span class=SpellE><span style='font-size:\n";
print "  14.0pt;font-family:Vrinda'>বিভাগ</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:2;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"ঢাকা \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>ঢাক</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>া</span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_01<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"খুলনা  \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>খুলন</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>া</span><span\n";
print "  style='font-size:14.0pt'><span style='mso-spacerun:yes'>  </span><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_35<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:3;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"গাজীপুর \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>গাজীপুর</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_02<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"চুয়াডাঙ্গা  \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>চুয়াডাঙ্গ</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>া</span><span\n";
print "  style='font-size:14.0pt'><span style='mso-spacerun:yes'>  </span><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_36<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:4;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"নারায়ণগঞ্জ \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>নারায়ণগঞ্জ</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_03<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"যশোর  \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>যশোর</span></span><span\n";
print "  style='font-size:14.0pt'><span style='mso-spacerun:yes'>  </span><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_37<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:5;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"নরসিংদী \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>নরসিংদ</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>ী</span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_04<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"ঝিনাইদহ  \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>ঝিনাইদহ</span></span><span\n";
print "  style='font-size:14.0pt'><span style='mso-spacerun:yes'>  </span><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_38<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:6;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"মানিকগঞ্জ \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>মানিকগঞ্জ</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_05<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"বাগেরহাট  \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>বাগেরহাট</span></span><span\n";
print "  style='font-size:14.0pt'><span style='mso-spacerun:yes'>  </span><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_39<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:7;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"মুন্সিগঞ্জ \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>মুন্সিগঞ্জ</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_06<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"কুষ্টিয়া  \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>কুষ্টিয</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>়া</span><span\n";
print "  style='font-size:14.0pt'><span style='mso-spacerun:yes'>  </span><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_40<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:8;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"গোপালগঞ্জ \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>ফরিদপুর</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_07<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"মাগুরা  \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>মাগুর</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>া</span><span\n";
print "  style='font-size:14.0pt'><span style='mso-spacerun:yes'>  </span><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_41<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:9;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"মাদারীপুর \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>গোপালগঞ্জ</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_08<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"মাগুরা  \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>মেহেরপুর</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_42<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:10;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"মাদারীপুর \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>মাদারীপুর</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_09<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"নড়াইল  \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>নড়াইল</span></span><span\n";
print "  style='font-size:14.0pt'><span style='mso-spacerun:yes'>  </span><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_43<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:11;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"রাজবাড়ী \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>রাজবাড</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>়ী</span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_10<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"সাতক্ষীরা \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>সাতক্ষীর</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>া</span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_44<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:12;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"শরিয়তপুর \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>শরিয়তপুর</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_11<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:13;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"ময়মনসিংহ \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>ময়মনসিংহ</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_12<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:14;height:.25in'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:.25in'\n";
print "  u1:str=\"জামালপুর \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>জামালপুর</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_13<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=274 colspan=2 style='width:205.75pt;padding:0in 0in 0in 0in;\n";
print "  height:.25in'>\n";
print "  <p class=MsoNormal align=center style='text-align:center'><span class=SpellE><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>রংপুর</span></span><span\n";
print "  style='font-size:14.0pt'> </span><span class=SpellE><span style='font-size:\n";
print "  14.0pt;font-family:Vrinda'>বিভাগ</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:15;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"কিশোরগঞ্জ \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>কিশোরগঞ্জ</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_14<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"রংপুর \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>রংপুর</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_45<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:16;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"নেত্রকোনা \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>নেত্রকোন</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>া</span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_15<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"দিনাজপুর \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>দিনাজপুর</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_46<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:17;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"শেরপুর \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>শেরপুর</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_16<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"গাইবান্ধা \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>গাইবান্ধ</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>া</span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_47<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:18;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>টাঙ্গাইল</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_17<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"কুড়িগ্রাম \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>কুড়িগ্রাম</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_48<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:19;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"নীলফামারী \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>নীলফামার</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>ী</span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_49<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:20;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"পঞ্চগড় \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>পঞ্চগড</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>়</span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_50<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:21;height:.25in'>\n";
print "  <td width=243 colspan=2 style='width:182.5pt;padding:0in 0in 0in 0in;\n";
print "  height:.25in'>\n";
print "  <p class=MsoNormal align=center style='text-align:center'><span class=SpellE><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>বরিশাল</span></span><span\n";
print "  style='font-size:14.0pt'> </span><span class=SpellE><span style='font-size:\n";
print "  14.0pt;font-family:Vrinda'>বিভাগ</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:.25in'\n";
print "  u1:str=\"ঠাকুরগাঁও \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>ঠাকুরগাঁও</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_51<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:22;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>বরিশাল</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_18<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"লালমনিরহাট \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>লালমনিরহাট</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_52<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:23;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>পটুয়াখাল</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>ী</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_19<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:24;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>ঝালকাঠ</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>ি</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_20<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:25;height:.25in'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>পিরোজপুর</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_21<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=274 colspan=2 style='width:205.75pt;padding:0in 0in 0in 0in;\n";
print "  height:.25in'>\n";
print "  <p class=MsoNormal align=center style='text-align:center'><span class=SpellE><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>রাজশাহ</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>ী</span><span\n";
print "  style='font-size:14.0pt'> </span><span class=SpellE><span style='font-size:\n";
print "  14.0pt;font-family:Vrinda'>বিভাগ</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:26;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>বরগুন</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>া</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_22<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>রাজশাহ</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>ী</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_53<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:27;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>ভোল</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>া</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_23<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>বগুড</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>়া</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_54<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:28;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>পাবন</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>া</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_55<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:29;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>জয়পুরহাট</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_56<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:30;height:.25in'>\n";
print "  <td width=243 colspan=2 style='width:182.5pt;padding:0in 0in 0in 0in;\n";
print "  height:.25in'>\n";
print "  <p class=MsoNormal align=center style='text-align:center'><span class=SpellE><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>চট্টগ্রাম</span></span><span\n";
print "  style='font-size:14.0pt'> </span><span class=SpellE><span style='font-size:\n";
print "  14.0pt;font-family:Vrinda'>বিভাগ</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>নওগ</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>াঁ</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_57<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:31;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>চট্টগ্রাম</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_24<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>নাটোর</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_58<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:32;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>কুমিল্ল</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>া</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_25<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>চাঁপাই</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'> নবাবগঞ্জ<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_59<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:33;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>ব্রাহ্মণবাড়ীয</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>়া</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_26<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>সিরাজগঞ্জ</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_60<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:34;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>চাঁদপুর</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_27<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:35;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>বান্দরবান</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_28<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:36;height:.25in'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>রাঙামাট</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>ি</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_29<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:.25in'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=274 colspan=2 style='width:205.75pt;padding:0in 0in 0in 0in;\n";
print "  height:.25in'>\n";
print "  <p class=MsoNormal align=center style='text-align:center'><span class=SpellE><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>সিলেট</span></span><span\n";
print "  style='font-size:14.0pt'> </span><span class=SpellE><span style='font-size:\n";
print "  14.0pt;font-family:Vrinda'>বিভাগ</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:37;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>খাগড়াছড</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>়ি</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_30<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>সিলেট</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_61<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:38;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>কক্সবাজার</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_31<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>মৌলভীবাজার</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_62<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:39;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><span\n";
print "  style='mso-spacerun:yes'> </span></span><span class=SpellE><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>ফেন</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>ী</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_32<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'\n";
print "  u1:str=\"হবিগঞ্জ \">\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>হবিগঞ্জ</span></span><span\n";
print "  style='font-size:14.0pt'> <o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_63<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:40;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>লক্ষীপুর</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_33<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>সুনামগঞ্জ</span></span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_64<o:p></o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:41;height:15.0pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span class=SpellE><span style='font-size:14.0pt;\n";
print "  font-family:Vrinda'>নোয়াখাল</span></span><span\n";
print "  style='font-size:14.0pt;font-family:Vrinda'>ী</span><span\n";
print "  style='font-size:14.0pt'><o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'>districts_34<o:p></o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:15.0pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print " <tr style='mso-yfti-irow:42;mso-yfti-lastrow:yes;height:12.75pt'>\n";
print "  <td width=113 style='width:85.0pt;padding:0in 0in 0in 0in;height:12.75pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.5pt;padding:0in 0in 0in 0in;height:12.75pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td style='padding:0in 0in 0in 0in;height:12.75pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=48 style='width:35.7pt;padding:0in 0in 0in 0in;height:12.75pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=144 style='width:1.5in;padding:0in 0in 0in 0in;height:12.75pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print "  <td width=130 style='width:97.75pt;padding:0in 0in 0in 0in;height:12.75pt'>\n";
print "  <p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "  </td>\n";
print " </tr>\n";
print "</table>\n";
print "Powered by <a href=\"http://www.jamunait.net/\" target=\"_blank\">\n";
print "<img src=\"http://www.jamunait.com/images/slogo.png\" alt=\"\" title=\"\" border=\"0\" width=\"132\" height=\"32\" hspace=\"10\"/></a>\n";
print "</div>\n";
print "\n";
print "<p class=MsoNormal><span style='font-size:14.0pt'><o:p> </o:p></span></p>\n";
print "\n";
print "</div>\n";
print "\n";
print "</body>\n";
print "\n";
print "</html>\n";

;

}

}
?>

